USE [master]
GO

/****** Object:  Database [CoffeeShop]    Script Date: 14/08/2024 5:43:06 CH ******/
CREATE DATABASE [CoffeeShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CoffeeShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CoffeeShop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CoffeeShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\CoffeeShop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CoffeeShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CoffeeShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CoffeeShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CoffeeShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CoffeeShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CoffeeShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [CoffeeShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CoffeeShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CoffeeShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CoffeeShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CoffeeShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CoffeeShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CoffeeShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CoffeeShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CoffeeShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CoffeeShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CoffeeShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CoffeeShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CoffeeShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CoffeeShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CoffeeShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CoffeeShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CoffeeShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CoffeeShop] SET RECOVERY FULL 
GO

ALTER DATABASE [CoffeeShop] SET  MULTI_USER 
GO

ALTER DATABASE [CoffeeShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CoffeeShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CoffeeShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CoffeeShop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CoffeeShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CoffeeShop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CoffeeShop] SET QUERY_STORE = ON
GO

ALTER DATABASE [CoffeeShop] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CoffeeShop] SET  READ_WRITE 
GO


USE [CoffeeShop]
GO

/****** Object:  Table [dbo].[employee]    Script Date: 14/08/2024 5:43:57 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[employee](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](150) NOT NULL,
	[Password] [nvarchar](150) NOT NULL,
	[Question] [nvarchar](150) NOT NULL,
	[Answer] [nvarchar](150) NOT NULL,
	[Date] [date] NULL,
 CONSTRAINT [PK_employee] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [CoffeeShop]
GO

/****** Object:  Table [dbo].[product]    Script Date: 14/08/2024 5:47:49 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[product](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[pro_id] [nvarchar](50) NOT NULL,
	[pro_name] [nvarchar](150) NOT NULL,
	[type] [nvarchar](150) NOT NULL,
	[stock] [int] NOT NULL,
	[price] [money] NOT NULL,
	[status] [nvarchar](100) NOT NULL,
	[image] [nvarchar](1550) NOT NULL,
	[date] [date] NULL,
 CONSTRAINT [PK_product] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [CoffeeShop]
GO

/****** Object:  Table [dbo].[customer]    Script Date: 14/08/2024 5:48:14 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[customer](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[customer_id] [int] NULL,
	[prod_id] [nvarchar](150) NULL,
	[prod_name] [nvarchar](150) NULL,
	[type] [nvarchar](150) NULL,
	[quantity] [int] NULL,
	[price] [money] NULL,
	[date] [date] NOT NULL,
	[image] [nvarchar](1550) NULL,
	[em_username] [nvarchar](150) NULL,
 CONSTRAINT [PK_customer] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

USE [CoffeeShop]
GO

/****** Object:  Table [dbo].[receipt]    Script Date: 14/08/2024 5:48:34 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[receipt](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[customer_id] [int] NULL,
	[total] [money] NULL,
	[date] [date] NOT NULL,
	[em_username] [nvarchar](150) NULL,
 CONSTRAINT [PK_receipt] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO